// packages/vuerd-app/src/components/Sash.vue
<script lang="tsx">
import { defineComponent, computed } from 'vue';
import { globalEvent, Move } from '@/helpers/event.helper';

const SIZE_SASH = 5;

export default defineComponent({
  props: {
    vertical: {
      type: Boolean,
      default: false,
    },
    horizontal: {
      type: Boolean,
      default: false,
    },
    top: {
      type: Number,
      default: 0,
    },
    left: {
      type: Number,
      default: 0,
    },
  },
  emits: {
    mousedownSash: (event: MouseEvent) => true,
    globalMove: (move: Move) => true,
  },
  setup(props, { emit }) {
    const classMap = computed(() => ({
      sash: true,
      vertical: props.vertical,
      horizontal: props.horizontal,
    }));

    const centerTop = computed(() =>
      props.top === 0 && !props.horizontal
        ? props.top
        : props.top - SIZE_SASH / 2
    );

    const centerLeft = computed(() =>
      props.left === 0 && !props.vertical
        ? props.left
        : props.left - SIZE_SASH / 2
    );

    const styleMap = computed(() => ({
      top: `${centerTop.value}px`,
      left: `${centerLeft.value}px`,
    }));

    const onMousedown = (event: MouseEvent) => {
      emit('mousedownSash', event);
      globalEvent.drag$.subscribe(move => {
        move.event.type === 'mousemove' && move.event.preventDefault();
        emit('globalMove', move);
      });
    };

    return () => (
      <div
        class={classMap.value}
        style={styleMap.value}
        onMousedown={onMousedown}
      />
    );
  },
});
</script>

<style scoped lang="scss">
$size-sash: 5px;

.sash {
  position: absolute;

  &.vertical {
    width: $size-sash;
    height: 100%;
    cursor: ew-resize;
  }

  &.horizontal {
    width: 100%;
    height: $size-sash;
    cursor: ns-resize;
  }
}
</style>

// packages/plugin-generate-template/src/components/Sash.tsx
import { FunctionalComponent } from 'preact';

import { Container } from '@/components/Sash.styled';
import { SIZE_SASH } from '@/core/layout';
import { useContext } from '@/hooks/useContext';
import { Move } from '@/internal-types/event.helper';

type Cursor =
  | 'default'
  | 'nwse-resize'
  | 'nesw-resize'
  | 'ew-resize'
  | 'ns-resize'
  | 'col-resize'
  | 'row-resize';

export interface Props {
  vertical: boolean;
  horizontal: boolean;
  edge: boolean;
  cursor: Cursor;
  top: number;
  left: number;
  onGlobalMove(move: Move): void;
  onMousedown(event: React.MouseEvent): void;
}

const Sash: FunctionalComponent<Partial<Props>> = ({
  vertical = false,
  horizontal = false,
  edge = false,
  cursor = 'default',
  top = 0,
  left = 0,
  onGlobalMove,
  onMousedown,
}) => {
  const context = useContext();

  const handleMousedown = (event: React.MouseEvent) => {
    if (!onGlobalMove) return;

    onMousedown && onMousedown(event);

    const { drag$ } = context.globalEvent;
    drag$.subscribe(move => {
      move.event.type === 'mousemove' && move.event.preventDefault();
      onGlobalMove(move);
    });
  };

  return (
    <Container
      style={{
        top: `${
          top === 0 && !horizontal && !edge ? top : top - SIZE_SASH / 2
        }px`,
        left: `${
          left === 0 && !vertical && !edge ? left : left - SIZE_SASH / 2
        }px`,
        cursor: edge ? cursor : '',
      }}
      vertical={vertical}
      horizontal={horizontal}
      edge={edge}
      onMouseDown={handleMousedown}
    />
  );
};

export default Sash;
